from Tree.avl_tree import *


def avl_tree_test():
    print("AVL Tree Test")
    avl = AVLTree()

    avl.insert(10)
    print(avl.root())
    avl.print()
    avl.insert(5)
    print(avl.root())
    avl.print()
    avl.insert(7)
    print(avl.root())
    avl.print()
    avl.insert(1)
    print(avl.root())
    avl.print()
    avl.insert(17)
    print(avl.root())
    avl.print()
    avl.insert(22)
    print(avl.root())
    avl.print()
    avl.insert(24)
    print(avl.root())
    avl.print()
    avl.insert(26)
    print(avl.root())
    avl.print()
    avl.insert(25)
    print(avl.root())
    avl.print()
    avl.insert(34)
    print(avl.root())
    avl.print()
    print(avl.height())
    print(avl.size())
    print(avl.get(0))
    print(avl.get(22))
    print(avl.empty())
    print(avl.root())
